name = "Perceptrons"
uuid = "933afed5-ab4b-5649-acc9-3edb4be3c343"
keywords = ["perceptrons", "machine learning", "artificial intelligence", "neural networks"]
license = "MIT"
desc = "A package with several types of Perceptron classifiers."
version = "1.0.0"

[deps]
JLD = "4138dd39-2aa7-5051-a626-17a0bb65d9c8"

[compat]
julia = "1.3"
JLD = "0.9.2"
