name = "Perceptrons"
uuid = "933afed5-ab4b-5649-acc9-3edb4be3c343"
keywords = ["perceptrons", "machine learning", "artificial intelligence", "neural networks"]
license = "MIT"
desc = "A package with several types of Perceptron classifiers."
version = "1.1.2"

[deps]
JLD = "4138dd39-2aa7-5051-a626-17a0bb65d9c8"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
julia = "1.3"
JLD = "0.9.2"
